export const PIX_CONSTANTS = {
  PAYLOAD_FORMAT_INDICATOR: '00',
  MERCHANT_ACCOUNT_INFORMATION: '26',
  MERCHANT_CATEGORY_CODE: '52',
  TRANSACTION_CURRENCY: '53',
  TRANSACTION_AMOUNT: '54',
  COUNTRY_CODE: '58',
  MERCHANT_NAME: '59',
  MERCHANT_CITY: '60',
  ADDITIONAL_DATA_FIELD: '62',
  CRC16: '63',
  CURRENCY_BRL: '986',
  COUNTRY_BR: 'BR',
};
